# Generated by Django 4.1.5 on 2023-01-26 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='post_body',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='timestamp',
            new_name='post_timestamp',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='post_user',
        ),
    ]
