# Generated by Django 4.1.4 on 2023-01-16 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_watchlise_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='watchlise',
            new_name='watchlist',
        ),
    ]
