# Generated by Django 4.1.4 on 2023-01-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_comment_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bid',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
