# Generated by Django 4.1.5 on 2023-01-18 03:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_bid_bid_alter_listing_bid_alter_listing_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name=django.core.validators.MinValueValidator(models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name=''))),
        ),
    ]
